# This file contains the tranfer objects (cannot fina a better name) whcih model the valid requests and responses
# generated by the API

from marshmallow import Schema, fields, post_load


class MixedTrafficScenarioRequest(object):
    def __init__(self, template_id, n_human_drivers, n_driving_agents):
        self.template_id = template_id
        self.n_human_drivers = n_human_drivers
        self.n_driving_agents = n_driving_agents


class MixedTrafficScenarioRequestSchema(Schema):

    template_id = fields.Integer()
    n_human_drivers = fields.Integer()
    n_driving_agents = fields.Integer()

    @post_load
    def make_mixed_traffic_scenario_request(self, data, **kwargs):
        return MixedTrafficScenarioRequest(**data)
