volumes:
  data:

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: Flexcrash
      MYSQL_USER: Flexcrash
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    volumes:
      - data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    image: flexcrash-app:7bb891d
    ports:  
      - "80:80"
    secrets:
        - db_password
        - flask_password
        - admin_user
        - admin_email
        - admin_password
    environment:
      MARIA_DB_HOST: db
      MARIA_DB_PORT: 3306
      MARIA_DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/flask_password
      ADMIN_USER_FILE: /run/secrets/admin_user
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      ADMIN_EMAIL_FILE: /run/secrets/admin_email
      
secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt
  flask_password:
    file: ./flask_password.txt
  admin_user:
    file: ./admin_user.txt
  admin_password:
    file: ./admin_password.txt
  admin_email:
    file: ./admin_email.txt
